#!/usr/bin/env bash

# Refresh scripts copied from github.

set -Eeuo pipefail

SCRIPT_DIR=$(dirname $(readlink -f "$0"))

# https://github.com/juven/maven-bash-completion
MAVEN_COMPLETION_SCRIPT="$SCRIPT_DIR/.bashrc.d/8maven-completion.bashrc"
MAVEN_COMPLETION_URL='https://raw.githubusercontent.com/juven/maven-bash-completion/master/bash_completion.bash'
curl --silent --output "$MAVEN_COMPLETION_SCRIPT" "$MAVEN_COMPLETION_URL"

# https://github.com/dysosmus/ansible-completion
for command in ansible ansible-doc ansible-galaxy ansible-playbook ansible-pull ansible-vault; do
  ANSIBLE_COMPLETION_SCRIPT="$SCRIPT_DIR/.bashrc.d/8$command-completion.bashrc"
  ANSIBLE_COMPLETION_URL="https://raw.githubusercontent.com/dysosmus/ansible-completion/master/$command-completion.bash"
  curl --silent --output "$ANSIBLE_COMPLETION_SCRIPT" "$ANSIBLE_COMPLETION_URL"
done

# Installing completion by calling quarkus command is slow !
# https://quarkus.io/guides/cli-tooling#shell-autocomplete-and-aliases
if type quarkus > /dev/null; then
  ANSIBLE_COMPLETION_SCRIPT="$SCRIPT_DIR/.bashrc.d/8quarkus-completion.bashrc"
  quarkus completion > "$ANSIBLE_COMPLETION_SCRIPT"
fi

# https://git.kernel.org/pub/scm/git/git.git/tree/contrib/diff-highlight
DIFF_HIGHLIGHT_SCRIPT='bin/diff-highlight'
DIFF_HIGHLIGHT_URL='https://git.kernel.org/pub/scm/git/git.git/plain/contrib/diff-highlight/'
echo '#!/usr/bin/perl' > "$DIFF_HIGHLIGHT_SCRIPT"
curl --silent "$DIFF_HIGHLIGHT_URL/DiffHighlight.pm" >> "$DIFF_HIGHLIGHT_SCRIPT"
curl --silent "$DIFF_HIGHLIGHT_URL/diff-highlight.perl" >> "$DIFF_HIGHLIGHT_SCRIPT"
