#!/usr/bin/env bash
# Refresh script copied from github.

SCRIPT_DIR=$(dirname $(readlink -f "$0"))

# https://github.com/dysosmus/ansible-completion
for command in ansible ansible-doc ansible-galaxy ansible-playbook ansible-pull ansible-vault; do
  curl --silent --output "$SCRIPT_DIR/.bashrc.d/8$command-completion.bashrc" "https://raw.githubusercontent.com/dysosmus/ansible-completion/master/$command-completion.bash"
done
